"""campos_y_estados_configurables

Revision ID: d1296f55e822
Revises: df5aadffe6f2
Create Date: 2026-06-08 14:45:56.464816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1296f55e822'
down_revision: Union[str, Sequence[str], None] = 'df5aadffe6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyecto_config_campos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('opciones', sa.Text(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proyecto_config_estados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('es_terminal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('requerimientos', sa.Column('estado_proyecto', sa.String(length=100), nullable=True))
    op.create_table('requerimiento_valor_campo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requerimiento_id', sa.Integer(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campo_id'], ['proyecto_config_campos.id'], ),
    sa.ForeignKeyConstraint(['requerimiento_id'], ['requerimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requerimiento_valor_campo')
    op.drop_table('proyecto_config_estados')
    op.drop_table('proyecto_config_campos')
    op.drop_column('requerimientos', 'estado_proyecto')
    # ### end Alembic commands ###
