"""estado inicial multi-tenant

Revision ID: df5aadffe6f2
Revises: 
Create Date: 2026-06-07 20:32:31.178741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5aadffe6f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requerimientos', sa.Column('proyecto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requerimientos', 'proyectos', ['proyecto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requerimientos', type_='foreignkey')
    op.drop_column('requerimientos', 'proyecto_id')
    # ### end Alembic commands ###
